import type { ParticipantRecord } from "@/data/interns/participants";

const STORAGE_KEY = "alva-intern-participants-v2";

const SESSION_FOCUS_GROUP: Record<string, string> = {
  "sess-001":
    "Discuss one habit young people have that older people always complain about.",
  "sess-002": "Debate whether remote work is better than going to the office every day.",
  "sess-003":
    "Talk about how social media has changed the way people communicate in Nigeria.",
  "sess-004": "Discuss what makes a voice sound trustworthy or authentic to you.",
  "sess-005":
    "Discuss one habit young people have that older people always complain about.",
  "sess-006": "Debate whether remote work is better than going to the office every day.",
  "sess-007":
    "Talk about how social media has changed the way people communicate in Nigeria.",
  "sess-008": "Discuss what makes a voice sound trustworthy or authentic to you.",
  "sess-009":
    "Discuss one habit young people have that older people always complain about.",
  "sess-010": "Debate whether remote work is better than going to the office every day.",
  "sess-011":
    "Talk about how social media has changed the way people communicate in Nigeria.",
  "sess-012": "Discuss what makes a voice sound trustworthy or authentic to you.",
};

function withFocusGroupSession(
  record: Omit<ParticipantRecord, "focusGroupSession"> & { focusGroupSession?: string }
): ParticipantRecord {
  return {
    ...record,
    focusGroupSession:
      record.focusGroupSession ||
      SESSION_FOCUS_GROUP[record.sessionId] ||
      "Focus group session",
  };
}

const MOCK_PARTICIPANT_SEEDS: Omit<ParticipantRecord, "focusGroupSession">[] = [
  {
    id: "p-001",
    sessionId: "sess-001",
    nameOrId: "Participant A-14",
    phone: "08012345678",
    ageBracket: "25-34",
    gender: "female",
    state: "Lagos",
    nativeLanguage: "Yoruba",
    sessionLanguage: "mixed",
    consent: "verbal",
    occupation: "Retail",
    loggedAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
  },
  {
    id: "p-002",
    sessionId: "sess-001",
    nameOrId: "Participant B-07",
    phone: "08023456789",
    ageBracket: "18-24",
    gender: "male",
    state: "Lagos",
    nativeLanguage: "Igbo",
    sessionLanguage: "mixed",
    consent: "signed",
    occupation: "Transport",
    loggedAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
  },
  {
    id: "p-003",
    sessionId: "sess-002",
    nameOrId: "Chioma O.",
    phone: "08034567890",
    ageBracket: "35-44",
    gender: "female",
    state: "FCT",
    nativeLanguage: "English",
    sessionLanguage: "english",
    consent: "verbal",
    occupation: "Healthcare",
    loggedAt: Date.now() - 1000 * 60 * 60 * 24 * 4,
  },
  {
    id: "p-004",
    sessionId: "sess-002",
    nameOrId: "Participant C-22",
    phone: "08045678901",
    ageBracket: "45-54",
    gender: "male",
    state: "Rivers",
    nativeLanguage: "Ikwerre",
    sessionLanguage: "pidgin",
    consent: "signed",
    occupation: "Construction",
    loggedAt: Date.now() - 1000 * 60 * 60 * 24 * 4,
  },
  {
    id: "p-005",
    sessionId: "sess-003",
    nameOrId: "Amaka N.",
    phone: "08056789012",
    ageBracket: "25-34",
    gender: "female",
    state: "Enugu",
    nativeLanguage: "Igbo",
    sessionLanguage: "english",
    consent: "verbal",
    occupation: "Education",
    loggedAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
  },
  {
    id: "p-006",
    sessionId: "sess-003",
    nameOrId: "Participant D-09",
    phone: "08067890123",
    ageBracket: "18-24",
    gender: "male",
    state: "Kano",
    nativeLanguage: "Hausa",
    sessionLanguage: "mixed",
    consent: "verbal",
    occupation: "Logistics",
    loggedAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
  },
  {
    id: "p-007",
    sessionId: "sess-003",
    nameOrId: "Participant E-31",
    phone: "08078901234",
    ageBracket: "55+",
    gender: "female",
    state: "Oyo",
    nativeLanguage: "Yoruba",
    sessionLanguage: "pidgin",
    consent: "signed",
    occupation: "Food service",
    loggedAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
  },
  {
    id: "p-008",
    sessionId: "sess-004",
    nameOrId: "Tunde A.",
    phone: "08089012345",
    ageBracket: "35-44",
    gender: "male",
    state: "Ogun",
    nativeLanguage: "Yoruba",
    sessionLanguage: "mixed",
    consent: "verbal",
    occupation: "Finance",
    loggedAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
  },
  {
    id: "p-009",
    sessionId: "sess-004",
    nameOrId: "Participant F-18",
    phone: "08090123456",
    ageBracket: "25-34",
    gender: "female",
    state: "Edo",
    nativeLanguage: "Edo",
    sessionLanguage: "english",
    consent: "signed",
    occupation: "Creative arts",
    loggedAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
  },
  {
    id: "p-010",
    sessionId: "sess-005",
    nameOrId: "Blessing U.",
    phone: "08101234567",
    ageBracket: "18-24",
    gender: "female",
    state: "Delta",
    nativeLanguage: "Urhobo",
    sessionLanguage: "pidgin",
    consent: "verbal",
    occupation: "Beauty & wellness",
    loggedAt: Date.now() - 1000 * 60 * 60 * 24,
  },
  {
    id: "p-011",
    sessionId: "sess-005",
    nameOrId: "Participant G-03",
    phone: "08112345678",
    ageBracket: "45-54",
    gender: "male",
    state: "Kaduna",
    nativeLanguage: "Hausa",
    sessionLanguage: "mixed",
    consent: "signed",
    occupation: "Agriculture",
    loggedAt: Date.now() - 1000 * 60 * 60 * 24,
  },
  {
    id: "p-012",
    sessionId: "sess-006",
    nameOrId: "Ngozi P.",
    phone: "08123456789",
    ageBracket: "25-34",
    gender: "female",
    state: "Anambra",
    nativeLanguage: "Igbo",
    sessionLanguage: "english",
    consent: "verbal",
    occupation: "Public sector",
    loggedAt: Date.now() - 1000 * 60 * 60 * 5,
  },
  {
    id: "p-013",
    sessionId: "sess-006",
    nameOrId: "Participant H-11",
    phone: "08134567890",
    ageBracket: "35-44",
    gender: "male",
    state: "Benue",
    nativeLanguage: "Tiv",
    sessionLanguage: "mixed",
    consent: "signed",
    occupation: "Civil service",
    loggedAt: Date.now() - 1000 * 60 * 60 * 4,
  },
  {
    id: "p-014",
    sessionId: "sess-007",
    nameOrId: "Fatima S.",
    phone: "08145678901",
    ageBracket: "25-34",
    gender: "female",
    state: "Kano",
    nativeLanguage: "Hausa",
    sessionLanguage: "pidgin",
    consent: "verbal",
    occupation: "Tailoring",
    loggedAt: Date.now() - 1000 * 60 * 60 * 24 * 6,
  },
  {
    id: "p-015",
    sessionId: "sess-007",
    nameOrId: "Participant I-26",
    phone: "08156789012",
    ageBracket: "18-24",
    gender: "male",
    state: "Plateau",
    nativeLanguage: "Berom",
    sessionLanguage: "english",
    consent: "signed",
    occupation: "Student",
    loggedAt: Date.now() - 1000 * 60 * 60 * 24 * 6,
  },
  {
    id: "p-016",
    sessionId: "sess-007",
    nameOrId: "Joy E.",
    phone: "08167890123",
    ageBracket: "45-54",
    gender: "female",
    state: "Cross River",
    nativeLanguage: "Efik",
    sessionLanguage: "mixed",
    consent: "verbal",
    occupation: "Hospitality",
    loggedAt: Date.now() - 1000 * 60 * 60 * 24 * 6,
  },
  {
    id: "p-017",
    sessionId: "sess-008",
    nameOrId: "Emeka D.",
    phone: "08178901234",
    ageBracket: "25-34",
    gender: "male",
    state: "Imo",
    nativeLanguage: "Igbo",
    sessionLanguage: "english",
    consent: "signed",
    occupation: "Tech",
    loggedAt: Date.now() - 1000 * 60 * 60 * 24 * 7,
  },
  {
    id: "p-018",
    sessionId: "sess-008",
    nameOrId: "Participant J-05",
    phone: "08189012345",
    ageBracket: "55+",
    gender: "female",
    state: "Osun",
    nativeLanguage: "Yoruba",
    sessionLanguage: "pidgin",
    consent: "verbal",
    occupation: "Trading",
    loggedAt: Date.now() - 1000 * 60 * 60 * 24 * 7,
  },
  {
    id: "p-019",
    sessionId: "sess-009",
    nameOrId: "Halima B.",
    phone: "08190123456",
    ageBracket: "35-44",
    gender: "female",
    state: "Sokoto",
    nativeLanguage: "Hausa",
    sessionLanguage: "mixed",
    consent: "signed",
    occupation: "Education",
    loggedAt: Date.now() - 1000 * 60 * 60 * 24 * 8,
  },
  {
    id: "p-020",
    sessionId: "sess-009",
    nameOrId: "Participant K-19",
    phone: "08201234567",
    ageBracket: "18-24",
    gender: "male",
    state: "Kwara",
    nativeLanguage: "Yoruba",
    sessionLanguage: "english",
    consent: "verbal",
    occupation: "Delivery",
    loggedAt: Date.now() - 1000 * 60 * 60 * 24 * 8,
  },
  {
    id: "p-021",
    sessionId: "sess-009",
    nameOrId: "Aisha M.",
    phone: "08212345678",
    ageBracket: "25-34",
    gender: "female",
    state: "Borno",
    nativeLanguage: "Kanuri",
    sessionLanguage: "mixed",
    consent: "signed",
    occupation: "NGO",
    loggedAt: Date.now() - 1000 * 60 * 60 * 24 * 8,
  },
  {
    id: "p-022",
    sessionId: "sess-010",
    nameOrId: "Victor O.",
    phone: "08223456789",
    ageBracket: "45-54",
    gender: "male",
    state: "Bayelsa",
    nativeLanguage: "Ijaw",
    sessionLanguage: "pidgin",
    consent: "verbal",
    occupation: "Oil & gas",
    loggedAt: Date.now() - 1000 * 60 * 60 * 24 * 9,
  },
  {
    id: "p-023",
    sessionId: "sess-010",
    nameOrId: "Participant L-08",
    phone: "08234567890",
    ageBracket: "25-34",
    gender: "female",
    state: "Nasarawa",
    nativeLanguage: "Eggon",
    sessionLanguage: "english",
    consent: "signed",
    occupation: "Banking",
    loggedAt: Date.now() - 1000 * 60 * 60 * 24 * 9,
  },
  {
    id: "p-024",
    sessionId: "sess-011",
    nameOrId: "Suleiman R.",
    phone: "08245678901",
    ageBracket: "35-44",
    gender: "male",
    state: "Kebbi",
    nativeLanguage: "Hausa",
    sessionLanguage: "mixed",
    consent: "verbal",
    occupation: "Farming",
    loggedAt: Date.now() - 1000 * 60 * 60 * 24 * 10,
  },
  {
    id: "p-025",
    sessionId: "sess-011",
    nameOrId: "Grace T.",
    phone: "08256789012",
    ageBracket: "18-24",
    gender: "female",
    state: "Akwa Ibom",
    nativeLanguage: "Ibibio",
    sessionLanguage: "pidgin",
    consent: "signed",
    occupation: "Media",
    loggedAt: Date.now() - 1000 * 60 * 60 * 24 * 10,
  },
  {
    id: "p-026",
    sessionId: "sess-011",
    nameOrId: "Participant M-33",
    phone: "08267890123",
    ageBracket: "55+",
    gender: "male",
    state: "Ekiti",
    nativeLanguage: "Yoruba",
    sessionLanguage: "english",
    consent: "verbal",
    occupation: "Retired teacher",
    loggedAt: Date.now() - 1000 * 60 * 60 * 24 * 10,
  },
  {
    id: "p-027",
    sessionId: "sess-012",
    nameOrId: "Zainab K.",
    phone: "08278901234",
    ageBracket: "25-34",
    gender: "female",
    state: "Zamfara",
    nativeLanguage: "Hausa",
    sessionLanguage: "mixed",
    consent: "signed",
    occupation: "Healthcare",
    loggedAt: Date.now() - 1000 * 60 * 60 * 24 * 11,
  },
  {
    id: "p-028",
    sessionId: "sess-012",
    nameOrId: "Participant N-02",
    phone: "08289012345",
    ageBracket: "35-44",
    gender: "male",
    state: "Taraba",
    nativeLanguage: "Jukun",
    sessionLanguage: "english",
    consent: "verbal",
    occupation: "Security",
    loggedAt: Date.now() - 1000 * 60 * 60 * 24 * 11,
  },
  {
    id: "p-029",
    sessionId: "sess-012",
    nameOrId: "Precious W.",
    phone: "08290123456",
    ageBracket: "18-24",
    gender: "female",
    state: "Abia",
    nativeLanguage: "Igbo",
    sessionLanguage: "pidgin",
    consent: "signed",
    occupation: "Fashion",
    loggedAt: Date.now() - 1000 * 60 * 60 * 24 * 11,
  },
  {
    id: "p-030",
    sessionId: "sess-004",
    nameOrId: "Participant O-17",
    phone: "08301234567",
    ageBracket: "45-54",
    gender: "male",
    state: "Gombe",
    nativeLanguage: "Fulfulde",
    sessionLanguage: "mixed",
    consent: "verbal",
    occupation: "Transport",
    loggedAt: Date.now() - 1000 * 60 * 60 * 24 * 1.5,
  },
];

const MOCK_PARTICIPANTS: ParticipantRecord[] =
  MOCK_PARTICIPANT_SEEDS.map(withFocusGroupSession);

function readStore(): ParticipantRecord[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return MOCK_PARTICIPANTS.map(withFocusGroupSession);
    const parsed = JSON.parse(raw) as ParticipantRecord[];
    const records = parsed.length > 0 ? parsed : MOCK_PARTICIPANTS;
    return records.map(withFocusGroupSession);
  } catch {
    return MOCK_PARTICIPANTS.map(withFocusGroupSession);
  }
}

function writeStore(records: ParticipantRecord[]) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(records));
}

export function loadParticipants(): ParticipantRecord[] {
  return readStore().sort((a, b) => b.loggedAt - a.loggedAt);
}

export function saveParticipantsBatch(records: ParticipantRecord[]) {
  const next = [...records, ...readStore().filter((item) => !records.some((r) => r.id === item.id))];
  writeStore(next);
}

export function saveParticipant(record: ParticipantRecord) {
  saveParticipantsBatch([record]);
}

export function hasLoggedParticipants(): boolean {
  return readStore().length > 0;
}

export function createSessionId() {
  return `sess-${crypto.randomUUID().slice(0, 8)}`;
}
